name: Build

on:
  push

env:
  PLUGIN_REPO: WorkingRobot/MyDalamudPlugins
  PROJECT_NAME: Craftimizer

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"

      - name: Restore
        run: |
          dotnet restore -r win ${{env.PROJECT_NAME}}.sln

      - name: Build
        run: |
          dotnet build --configuration Release

      - name: Test
        run: |
          dotnet test --configuration Release --logger "trx;logfilename=results.trx" --logger "html;logfilename=results.html" --logger "console;verbosity=detailed" --results-directory="TestResults"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.PROJECT_NAME}}
          path: ${{env.PROJECT_NAME}}/bin/x64/Release/${{env.PROJECT_NAME}}
          if-no-files-found: error

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: ${{env.PROJECT_NAME}}
          path: TestResults

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        id: release
        with:
          files: ${{env.PROJECT_NAME}}/bin/x64/Release/${{env.PROJECT_NAME}}/*

      - name: Trigger Plugin Repo Update
        uses: peter-evans/repository-dispatch@v2
        if: ${{ steps.release.conclusion == 'success' }}
        with:
          token: ${{secrets.PAT}}
          repository: ${{env.PLUGIN_REPO}}
          event-type: new-release